#ifndef CONFIG_H
#define CONFIG_H

#define LIBORIGIN_VERSION_MAJOR 3
#define LIBORIGIN_VERSION_MINOR 0
#define LIBORIGIN_VERSION_PATCH 3
#define LIBORIGIN_VERSION ((LIBORIGIN_VERSION_MAJOR << 16) | (LIBORIGIN_VERSION_MINOR << 8) | LIBORIGIN_VERSION_PATCH)
#define LIBORIGIN_VERSION_STRING "3.0.3"

#endif
