set(SOURCES
    # src/analysis
    src/analysis/Anova.cpp
    src/analysis/ChiSquareTest.cpp
    src/analysis/Convolution.cpp
    src/analysis/Correlation.cpp
    src/analysis/Differentiation.cpp
    src/analysis/ExponentialFit.cpp
    src/analysis/FFT.cpp
    src/analysis/FFTFilter.cpp
    src/analysis/Filter.cpp
    src/analysis/Fit.cpp
    src/analysis/Integration.cpp
    src/analysis/Interpolation.cpp
    src/analysis/LogisticFit.cpp
    src/analysis/MultiPeakFit.cpp
    src/analysis/NonLinearFit.cpp
    src/analysis/PluginFit.cpp
    src/analysis/PolynomialFit.cpp
    src/analysis/ShapiroWilkTest.cpp
    src/analysis/SigmoidalFit.cpp
    src/analysis/SmoothFilter.cpp
    src/analysis/StatisticTest.cpp
    src/analysis/Statistics.cpp
    src/analysis/fft2D.cpp
    src/analysis/fit_gsl.cpp
    src/analysis/tTest.cpp
    # src/analysis/dialogs
    src/analysis/dialogs/AnovaDialog.cpp
    src/analysis/dialogs/BaselineDialog.cpp
    src/analysis/dialogs/ExpDecayDialog.cpp
    src/analysis/dialogs/FFTDialog.cpp
    src/analysis/dialogs/FilterDialog.cpp
    src/analysis/dialogs/FitDialog.cpp
    src/analysis/dialogs/FrequencyCountDialog.cpp
    src/analysis/dialogs/GriddingDialog.cpp
    src/analysis/dialogs/IntDialog.cpp
    src/analysis/dialogs/IntegrationDialog.cpp
    src/analysis/dialogs/InterpolationDialog.cpp
    src/analysis/dialogs/PolynomFitDialog.cpp
    src/analysis/dialogs/SmoothCurveDialog.cpp
    src/analysis/dialogs/StudentTestDialog.cpp
    src/analysis/dialogs/SubtractDataDialog.cpp
    # src/core
    src/core/ApplicationSettings.cpp
    src/core/ApplicationWindow.cpp
    src/core/ConfigDialog.cpp
    src/core/FittingConfigPage.cpp
    src/core/GeneralConfigPage.cpp
    src/core/NotesConfigPage.cpp
    src/core/Plots2DConfigPage.cpp
    src/core/Plots3DConfigPage.cpp
    src/core/TablesConfigPage.cpp
    src/core/CrashHandler.cpp
    src/core/CreateBinMatrixDialog.cpp
    src/core/CustomActionDialog.cpp
    src/core/FindDialog.cpp
    src/core/Folder.cpp
    src/core/ProjectManager.cpp
    src/core/ProjectSerializer.cpp
  src/core/ActionTranslator.cpp
  src/core/MenuBuilder.cpp
  src/core/ActionManager.cpp
    src/core/ImportASCIIDialog.cpp
    src/core/Logger.cpp
    src/core/MdiSubWindow.cpp
    src/core/ObjectRegistry.cpp
    src/core/OpenProjectDialog.cpp
    src/core/PlotWizard.cpp
    src/core/QtiPlotApplication.cpp
    src/core/RenameWindowDialog.cpp
    src/core/main.cpp
    # src/excel
    src/excel/ExcelFileConverter.cpp
    # src/lib/3rdparty/qtcolorpicker/src
    src/lib/3rdparty/qtcolorpicker/src/qtcolorpicker.cpp
    # src/lib/src
    src/lib/src/AllocLedger.cpp
    src/lib/src/CollapsiveGroupBox.cpp
    src/lib/src/ColorBox.cpp
    src/lib/src/ColorButton.cpp
    src/lib/src/ColorMapEditor.cpp
    src/lib/src/DoubleSpinBox.cpp
    src/lib/src/ExtensibleFileDialog.cpp
    src/lib/src/LineNumberDisplay.cpp
    src/lib/src/LinearColorMap.cpp
    src/lib/src/PatternBox.cpp
    src/lib/src/PenStyleBox.cpp
    src/lib/src/SymbolBox.cpp
    src/lib/src/SymbolDialog.cpp
    src/lib/src/TextFormatButtons.cpp
    # src/matrix
    src/matrix/ColorMapDialog.cpp
    src/matrix/Matrix.cpp
    src/matrix/MatrixCommand.cpp
    src/matrix/MatrixDialog.cpp
    src/matrix/MatrixModel.cpp
    src/matrix/MatrixResamplingDialog.cpp
    src/matrix/MatrixSizeDialog.cpp
    src/matrix/MatrixValuesDialog.cpp
    # src/plot2D
    src/plot2D/AddWidgetTool.cpp
    src/plot2D/ArrowMarker.cpp
    src/plot2D/BoxCurve.cpp
    src/plot2D/CanvasPicker.cpp
    src/plot2D/CurveDecimator.cpp
    src/plot2D/DataPickerTool.cpp
    src/plot2D/EllipseWidget.cpp
    src/plot2D/ErrorBarsCurve.cpp
    src/plot2D/FrameWidget.cpp
    src/plot2D/FunctionCurve.cpp
    src/plot2D/Graph.cpp
    src/plot2D/Grid.cpp
    src/plot2D/ImageSymbol.cpp
    src/plot2D/ImageWidget.cpp
    src/plot2D/LegendCommand.cpp
    src/plot2D/LegendWidget.cpp
    src/plot2D/LineProfileTool.cpp
    src/plot2D/LnScaleEngine.cpp
    src/plot2D/Log2ScaleEngine.cpp
    src/plot2D/LogitScaleEngine.cpp
    src/plot2D/MultiLayer.cpp
    src/plot2D/MultiPeakFitTool.cpp
    src/plot2D/PieCurve.cpp
    src/plot2D/PlotCommand.cpp
    src/plot2D/PlotCurve.cpp
    src/plot2D/PolarGraph.cpp
    src/plot2D/ProbabilityScaleEngine.cpp
    src/plot2D/QwtBarCurve.cpp
    src/plot2D/QwtHistogram.cpp
    src/plot2D/RangeSelectorTool.cpp
    src/plot2D/ReciprocalScaleEngine.cpp
    src/plot2D/RectangleWidget.cpp
    src/plot2D/ScaleDraw.cpp
    src/plot2D/ScaleEngine.cpp
    src/plot2D/ScalePicker.cpp
    src/plot2D/ScreenPickerTool.cpp
    src/plot2D/SelectionMoveResizer.cpp
    src/plot2D/Spectrogram.cpp
    src/plot2D/SubtractLineTool.cpp
    src/plot2D/TexWidget.cpp
    src/plot2D/TitlePicker.cpp
    src/plot2D/TranslateCurveTool.cpp
    src/plot2D/VectorCurve.cpp
    # src/plot2D/dialogs
    src/plot2D/dialogs/AssociationsDialog.cpp
    src/plot2D/dialogs/AxesDialog.cpp
    src/plot2D/dialogs/ContourLinesEditor.cpp
    src/plot2D/dialogs/CurveRangeDialog.cpp
    src/plot2D/dialogs/CurvesDialog.cpp
    src/plot2D/dialogs/EnrichmentDialog.cpp
    src/plot2D/dialogs/ErrDialog.cpp
    src/plot2D/dialogs/FunctionDialog.cpp
    src/plot2D/dialogs/ImageExportDialog.cpp
    src/plot2D/dialogs/LayerDialog.cpp
    src/plot2D/dialogs/LineDialog.cpp
    src/plot2D/dialogs/PlotDialog.cpp
    src/plot2D/dialogs/PolarSettingsDialog.cpp
    src/plot2D/dialogs/TextDialog.cpp
    src/plot2D/dialogs/TextEditor.cpp
    # src/plot3D
    src/plot3D/ColorMapPreviewDialog.cpp
    src/plot3D/Graph3D.cpp
    src/plot3D/LinearColor.cpp
    src/plot3D/Plot3DDialog.cpp
    src/plot3D/SurfaceDialog.cpp
    # src/scripting
    src/scripting/FindReplaceDialog.cpp
    src/scripting/MyParser.cpp
    src/scripting/Note.cpp
    src/scripting/PythonScript.cpp
    src/scripting/PythonScripting.cpp
    src/scripting/PythonSyntaxHighlighter.cpp
    src/scripting/Script.cpp
    src/scripting/ScriptEdit.cpp
    src/scripting/ScriptUndoScope.cpp
    src/scripting/ScriptWindow.cpp
    src/scripting/ScriptingEnv.cpp
    src/scripting/ScriptingLangDialog.cpp
    src/scripting/muParserScript.cpp
    src/scripting/muParserScripting.cpp
    # src/table
    src/table/ExportDialog.cpp
    src/table/ExtractDataDialog.cpp
    src/table/SetColValuesDialog.cpp
    src/table/SortDialog.cpp
    src/table/Table.cpp
    src/table/TableCommand.cpp
    src/table/TableDialog.cpp
    src/table/TableStatistics.cpp
)

set(HEADERS
    # src/analysis
    src/analysis/Anova.h
    src/analysis/ChiSquareTest.h
    src/analysis/Convolution.h
    src/analysis/Correlation.h
    src/analysis/Differentiation.h
    src/analysis/ExponentialFit.h
    src/analysis/FFT.h
    src/analysis/FFTFilter.h
    src/analysis/Filter.h
    src/analysis/Fit.h
    src/analysis/Integration.h
    src/analysis/Interpolation.h
    src/analysis/LogisticFit.h
    src/analysis/MultiPeakFit.h
    src/analysis/NonLinearFit.h
    src/analysis/PluginFit.h
    src/analysis/PolynomialFit.h
    src/analysis/ShapiroWilkTest.h
    src/analysis/SigmoidalFit.h
    src/analysis/SmoothFilter.h
    src/analysis/StatisticTest.h
    src/analysis/Statistics.h
    src/analysis/fft2D.h
    src/analysis/fit_gsl.h
    src/analysis/tTest.h
    # src/analysis/dialogs
    src/analysis/dialogs/AnovaDialog.h
    src/analysis/dialogs/BaselineDialog.h
    src/analysis/dialogs/ExpDecayDialog.h
    src/analysis/dialogs/FFTDialog.h
    src/analysis/dialogs/FilterDialog.h
    src/analysis/dialogs/FitDialog.h
    src/analysis/dialogs/FrequencyCountDialog.h
    src/analysis/dialogs/GriddingDialog.h
    src/analysis/dialogs/IntDialog.h
    src/analysis/dialogs/IntegrationDialog.h
    src/analysis/dialogs/InterpolationDialog.h
    src/analysis/dialogs/PolynomFitDialog.h
    src/analysis/dialogs/SmoothCurveDialog.h
    src/analysis/dialogs/StudentTestDialog.h
    src/analysis/dialogs/SubtractDataDialog.h
    # src/core
    src/core/ApplicationSettings.h
    src/core/ApplicationWindow.h
    src/core/ConfigDialog.h
    src/core/ConfigPage.h
    src/core/FittingConfigPage.h
    src/core/GeneralConfigPage.h
    src/core/NotesConfigPage.h
    src/core/Plots2DConfigPage.h
    src/core/Plots3DConfigPage.h
    src/core/TablesConfigPage.h
    src/core/CrashHandler.h
    src/core/CreateBinMatrixDialog.h
    src/core/CustomActionDialog.h
    src/core/FindDialog.h
    src/core/Folder.h
    src/core/ProjectManager.h
    src/core/ProjectSerializer.h
  src/core/ActionTranslator.h
  src/core/MenuBuilder.h
  src/core/ActionManager.h
    src/core/ImportASCIIDialog.h
    src/core/ImportExportPlugin.h
    src/core/Logger.h
    src/core/MdiSubWindow.h
    src/core/ObjectId.h
    src/core/ObjectRegistry.h
    src/core/OpenProjectDialog.h
    src/core/PlotWizard.h
    src/core/QtiPlotApplication.h
    src/core/Ref.h
    src/core/RenameWindowDialog.h
    src/core/globals.h
    # src/excel
    src/excel/ExcelFileConverter.h
    # src/lib/3rdparty/qtcolorpicker/src
    src/lib/3rdparty/qtcolorpicker/src/qtcolorpicker.h
    # src/lib/include
    src/lib/include/CollapsiveGroupBox.h
    src/lib/include/ColorBox.h
    src/lib/include/ColorButton.h
    src/lib/include/ColorMapEditor.h
    src/lib/include/DoubleSpinBox.h
    src/lib/include/ExtensibleFileDialog.h
    src/lib/include/LineNumberDisplay.h
    src/lib/include/LinearColorMap.h
    src/lib/include/PatternBox.h
    src/lib/include/PenStyleBox.h
    src/lib/include/SymbolBox.h
    src/lib/include/SymbolDialog.h
    src/lib/include/TextFormatButtons.h
    src/lib/include/Tracked.h
    # src/matrix
    src/matrix/ColorMapDialog.h
    src/matrix/Matrix.h
    src/matrix/MatrixCommand.h
    src/matrix/MatrixDialog.h
    src/matrix/MatrixModel.h
    src/matrix/MatrixResamplingDialog.h
    src/matrix/MatrixSizeDialog.h
    src/matrix/MatrixValuesDialog.h
    # src/plot2D
    src/plot2D/AddWidgetTool.h
    src/plot2D/ArrowMarker.h
    src/plot2D/BoxCurve.h
    src/plot2D/CanvasPicker.h
    src/plot2D/CurveDecimator.h
    src/plot2D/DataPickerTool.h
    src/plot2D/EllipseWidget.h
    src/plot2D/ErrorBarsCurve.h
    src/plot2D/FrameWidget.h
    src/plot2D/FunctionCurve.h
    src/plot2D/Graph.h
    src/plot2D/Grid.h
    src/plot2D/ImageSymbol.h
    src/plot2D/ImageWidget.h
    src/plot2D/LegendCommand.h
    src/plot2D/LegendWidget.h
    src/plot2D/LineProfileTool.h
    src/plot2D/LnScaleEngine.h
    src/plot2D/Log2ScaleEngine.h
    src/plot2D/LogitScaleEngine.h
    src/plot2D/MultiLayer.h
    src/plot2D/MultiPeakFitTool.h
    src/plot2D/PieCurve.h
    src/plot2D/PlotCommand.h
    src/plot2D/PlotCurve.h
    src/plot2D/PlotToolInterface.h
    src/plot2D/PolarGraph.h
    src/plot2D/ProbabilityScaleEngine.h
    src/plot2D/QwtBarCurve.h
    src/plot2D/QwtHistogram.h
    src/plot2D/RangeSelectorTool.h
    src/plot2D/ReciprocalScaleEngine.h
    src/plot2D/RectangleWidget.h
    src/plot2D/ScaleDraw.h
    src/plot2D/ScaleEngine.h
    src/plot2D/ScalePicker.h
    src/plot2D/ScreenPickerTool.h
    src/plot2D/SelectionMoveResizer.h
    src/plot2D/Spectrogram.h
    src/plot2D/SubtractLineTool.h
    src/plot2D/TexWidget.h
    src/plot2D/TitlePicker.h
    src/plot2D/TranslateCurveTool.h
    src/plot2D/VectorCurve.h
    # src/plot2D/dialogs
    src/plot2D/dialogs/AssociationsDialog.h
    src/plot2D/dialogs/AxesDialog.h
    src/plot2D/dialogs/ContourLinesEditor.h
    src/plot2D/dialogs/CurveRangeDialog.h
    src/plot2D/dialogs/CurvesDialog.h
    src/plot2D/dialogs/EnrichmentDialog.h
    src/plot2D/dialogs/ErrDialog.h
    src/plot2D/dialogs/FunctionDialog.h
    src/plot2D/dialogs/ImageExportDialog.h
    src/plot2D/dialogs/LayerDialog.h
    src/plot2D/dialogs/LineDialog.h
    src/plot2D/dialogs/PlotDialog.h
    src/plot2D/dialogs/PolarSettingsDialog.h
    src/plot2D/dialogs/TextDialog.h
    src/plot2D/dialogs/TextEditor.h
    # src/plot3D
    src/plot3D/ColorMapPreviewDialog.h
    src/plot3D/Graph3D.h
    src/plot3D/LinearColor.h
    src/plot3D/Plot3DDialog.h
    src/plot3D/SurfaceDialog.h
    # src/scripting
    src/scripting/FindReplaceDialog.h
    src/scripting/MyParser.h
    src/scripting/Note.h
    src/scripting/PythonScript.h
    src/scripting/PythonScripting.h
    src/scripting/PythonSyntaxHighlighter.h
    src/scripting/Script.h
    src/scripting/ScriptEdit.h
    src/scripting/ScriptUndoScope.h
    src/scripting/ScriptWindow.h
    src/scripting/ScriptingEnv.h
    src/scripting/ScriptingLangDialog.h
    src/scripting/customevents.h
    src/scripting/muParserScript.h
    src/scripting/muParserScripting.h
    # src/table
    src/table/ExportDialog.h
    src/table/ExtractDataDialog.h
    src/table/SetColValuesDialog.h
    src/table/SortDialog.h
    src/table/Table.h
    src/table/TableCommand.h
    src/table/TableDialog.h
    src/table/TableStatistics.h
)
