[build-system]
requires = ["sip >=6, <7", "PyQt-builder >=1, <2"]
build-backend = "sipbuild.api"

[project]
name = "qti"

[tool.sip.project]
abi-version = "13.9"
sip-files-dir = "qtiplot/src/scripting"
sip-include-dirs = [
    "/usr/lib/python3/dist-packages/PyQt6/bindings",
    "/usr/share/sip/PyQt6"
]
sip-module = "PyQt6.sip"

[tool.sip.bindings.qti]
sip-file = "qti.sip"
headers = ["qtiplot/src/scripting/PythonScripting.h"]
include-dirs = ["qtiplot/src/core", "qtiplot/src/lib/include", "qtiplot/src/plot2D", "qtiplot/src/plot3D", "qtiplot/src/matrix", "qtiplot/src/table", "qtiplot/src/scripting"]
